"""
script that works with parstubuilder to compress simulation vtk files
for a parametric study.
"""
import tarfile
import datetime as dt
import shutil
import os


# name of the parametric study who's data you wish to compress
studyDir = '/absolute/path/to/parstubuilder/parametric/study/directory'

# -----------------------------------------------------------------
# get list of simulation directories from parStudyInfo.txt file 
# (generated by parstubuilder)
# -----------------------------------------------------------------

simList = []
with open(studyDir+'/parStudyInfo.txt') as fin:
    for line in fin:
        if 'Unique parameter set' in line:
            break
    for line in fin:
        simList.append(line.rstrip())
fin.close()

# -----------------------------------------------------------------
# use tar to archive and compress each simulation's vtk data
# -----------------------------------------------------------------

logName = 'compressError.log'
print('\n\nBEGINNING DATA COMPRESSION FOR PARAMETRIC STUDY STORED IN:\n')
print(studyDir+'\n')
for pth in sorted(simList):

    # name of directory to compress
    dirName = studyDir+'/'+pth+'/vtkoutput'
    # name of archive file
    arName = dirName+'.tar.gz'
    try:
        with tarfile.open(arName, "w:gz") as tar:
            tar.add(dirName,arcname=os.path.basename(dirName))
        print('- successfully compressed and archived: '+dirName)
        print()
        # remove the data directory
        shutil.rmtree(dirName)
    except Exception as tarError:
        # log errors
        fullLogName = studyDir+'/'+pth+'/'+logName
        print('\n- An exception was thrown while trying to compress the following directory:\n')
        print('\t'+dirName+'\n')
        print('\t* writing error info on '+fullLogName)
        # write the log file
        with open(fullLogName,"w") as log:
            log.write(str(dt.datetime.now())+'\n')
            log.write('encountered exception of type: '+str(type(tarError))+'\n')
            log.write(str(tarError))
